src/App.css
src/widgets/Layout/BottomBar.tsx

- #6 
- BottomBar 공용 컴포넌트 개발
- 메인페이지 구현에서 그라데이션 쓰신 것보고 착안하여 바텀바에서도 그라데이션 적용해보았습니다.

feat: BottomBar 개발

---

src/pages/NotFound/NotFoundPage.tsx
src/widgets/Layout/BottomBar.tsx
src/widgets/Layout/Header.tsx
src/widgets/Layout/Layout.tsx

- #23 
- 레이아웃 파일 main 태그 내 배경 그라데이션 지정
- 바텀바 여백 조정
- 헤더 색상 고정
각 페이지 내 예외되는 경우가 아니라면 배경을 지정하지 않아야 그라데이션 배경이 잘 보입니다!
최대한 비슷하게 해봤으나.. 기술적으로 완벽히는 추후 더 연구해보겠습니다.

refact: 기본 레이아웃 리팩토링

---

.github/workflows/deploy.yml

fix: main vercel deply수정

---

vercel.json
vite.config.ts

fix: 임시 pwa 비활성화

---

src/features/archive/hooks/useArchivedAlbums.ts
src/features/archive/hooks/useArchivedArtists.ts
src/features/archive/hooks/useArchivedTracks.ts
src/features/my/hooks/useProfile.ts
src/pages/Archive/Album/AlbumPage.tsx
src/pages/Archive/Artist/ArtistPage.tsx
src/pages/Archive/Music/MusicPage.tsx
src/pages/My/MyPage.tsx
vercel.json

fix: 배포환경 api 호출형태 변경

---

src/features/notification/hooks/useFriendRequestActions.ts
src/features/notification/hooks/useSendFriendRequest.ts
src/pages/Notification/NotificationDetailPage.tsx
src/pages/Profile/ProfileDetailPage.tsx
src/shared/ui/atoms/Toast.tsx
src/store/friendApi.ts

- #76 
- 친구 요청 신청 api 연동 (이미 보낸 경우에는 토스트 메시지로 이미 보냈다고 알림)
- 친구 요청 수락 api 연동
- 친구 요청 거절 api 연동

Feat: 알림 페이지 친구 관련 api 연동

---

src/pages/Login/LoginPage.tsx
vercel.json

- #79 
- 서버에서 회원가입 요청 시 405 Method Not Allowed 오류 발생 문제 해결을 위한 임시 테스트 코드 수정
- 로그인 페이지 플레이스홀더 수정

feat: 회원 페이지 리다이렉트 추가 및 로그인 페이지 플레이스홀더 수정

---

src/pages/My/MyPage.tsx
src/pages/My/_components/ProfileInfoSkeleton.tsx
src/pages/Notification/NotificationPage.tsx
src/pages/Notification/_components/NotificationItem.tsx
src/pages/Notification/_components/NotificationItemSkeleton.tsx
src/pages/Notification/_components/NotificationList.tsx
src/pages/Notification/_components/NotificationListSkeleton.tsx
src/pages/Profile/OtherProfile.tsx

- #80 
- 마이페이지, 타 유저페이지에서 이미 구현해둔 스켈레톤 UI 파일 연결 (ProfileInfoSkeleton, HashTagListSkeleton, ArtistGridSkeleton, MusicListSkeleton, MyArchiveItemSkeletonList)
- 알림페이지에서 스켈레톤 UI 구현 및 연결 (NotificationItemSkeleton, NotificationListSkeleton)

refact: 스켈레톤 UI 적용

---

src/pages/Signup/SignupVerifyPage.tsx

feat: 회원가입 인증번호 재전송 기능 추가 및 UI 개선

---

src/pages/Archive/Music/_components/ColoredFolder.tsx

- #91 
- 폴더 아이콘 문제로 배포 환경에서 아이콘이 표시되지 않는 문제 해결 시도

refact: 폴더 아이콘 경로 수정

---

src/pages/Signup/SignupCompletePage.tsx
src/pages/Signup/SignupPage.tsx
src/pages/Signup/SignupVerifyPage.tsx
src/store/auth.ts

[feat] 회원가입 인증 관련 오류 수정 

---

src/pages/chat/_components/PrivateChatMessageItem.tsx
src/pages/chat/_components/PrivateChatMessageList.tsx
src/widgets/Layout/BottomBar.tsx

- #104 
- 개인 채팅 페이지 ui 임시 변경
- 바텀바 탐색 페이지 폐기에 따른 변경

refact: 개인 채팅 페이지 UI 수정 및 바텀바 수정

---

src/pages/Signup/SignupCompletePage.tsx

feat: 회원가입 완료 페이지에서 버튼 텍스트 및 네비게이션 경로 변경

---

.github/workflows/deploy-release.yml
src/api/API.ts
src/features/setting/hooks/useAuth.ts
src/shared/utils/authCleanup.ts
vercel.json

fix : 리프레시 토큰 및 aws 배포 deploy 세팅

---

src/pages/Join/_components/chat/NormalChat.tsx

- #97 
- merge conflict 도중 발생한 에러 수정

fix: props 관련 build error 수정

---

src/pages/Home/HomePage.tsx
src/store/userStore.ts

fix : TypeScript 린터 에러 수정 및 콘솔 로그 최적화

---

src/pages/Home/HomePage.tsx
src/pages/Home/_components/BandInfoModal.tsx
src/pages/Home/_components/TagList.tsx
src/store/userStore.ts

fix : lint errer 수정

---

README.md

doc : 4번까지 문서 수정

---

eslint.config.cjs
src/pages/Home/HomePage.tsx
src/pages/chat/hooks/useChat.ts
src/pages/chat/hooks/usePrivateChat.ts
src/pages/chat/hooks/useWebSocket.ts

feat: eslint 에러 수정

---

README.md

docs: README 컨벤션 노션 페이지 추가

---

src/api/API.ts
src/app/router.tsx
src/features/my/hooks/useProfileEdit.ts
src/pages/My/_components/ProfileInfo.tsx
src/pages/My/edit/MyEditPage.tsx
src/pages/My/edit/_components/ArtistCard.tsx
src/pages/My/edit/_components/ArtistSection.tsx
src/pages/My/edit/_components/BasicInfoSection.tsx
src/pages/My/edit/_components/GenreSection.tsx
src/pages/My/edit/_components/IntroductionSection.tsx
src/pages/My/edit/_components/KeywordSection.tsx
src/pages/My/edit/_components/LocationSection.tsx
src/pages/My/edit/_components/ProfileEditHeader.tsx
src/pages/My/edit/_components/ProfileImageSection.tsx
src/pages/My/edit/_components/ProfileTag.tsx
src/pages/My/edit/_components/SessionIcon.tsx
src/pages/My/edit/_components/SessionSection.tsx
src/store/profileApi.ts

- #126 
- 현재 닉네임, 나이, 거주지, 성별, 자기소개, 프로필 이미지 수정 가능합니다.
세션, 선호 아티스트, 키워드, 장르 관련 수정은 서버 api 관련 필드 저장에 오류가 있어 담당 백엔드 개발자분께서 추후 수정해준다고 하셨습니다. 이후 확인되면 저도 맞추어 수정 마저 하겠습니다.

feat: 내 프로필 수정 1차 구현 및 연동

---

src/pages/Join/BandRecruit.tsx
src/pages/Join/_components/band_recruit/RecruitChat.tsx
src/pages/Join/_components/chat/BandChat.tsx

feat: BandRecruit, Join 밴드 채팅방 routing 연결

---

src/pages/Join/saved_band/SavedBandDetail.tsx

- #이슈번호
- feat: SavedBandDetail SessionSelectModal -> 밴드 채팅방 연결 flow 구현

feat: SavedBandDetail SessionSelectModal 연결

---

src/pages/Join/_components/chat/BandChat.tsx
src/pages/Join/_components/chat/NormalChat.tsx
src/pages/chat/PrivateChatPage.tsx
src/pages/chat/hooks/usePrivateChat.ts
src/services/WebSocketService.ts

- #137 
- 밴드 매니저와 지원자와의 개인 채팅방 연결

feat: 밴드 매니저와 지원자의 채팅 연결

---

src/pages/pretest/artist/PretestArtistPage.tsx
src/pages/pretest/profile/PretestProfileCompletePage.tsx
src/pages/pretest/session/PretestSessionPage.tsx

- #이슈번호
- 사전테스트 연동 pr 에러 수정
현재상황 히스토리 설명할게요
[feat/pre-test-v2](https://github.com/UMC-Banddy/client/tree/feat/pre-test-v2) 브랜치에서 
1. 자정에 제가 카톡으로 사전테스트 연동했고, 로컬에서 테스트 결과, 디비에 정상적으로 올라가는데 
사전테스트 완료페이지에서 사전테스트값들이 더미데이터로만 나와서 이거 수정한다고 말씀드림. 
-> 여기까지 한 거 1차 커밋 올림 ([feat: 사전테스트 연동 완료](https://github.com/UMC-Banddy/client/pull/142/commits/dc50f6fd0f2ec67b2c1ff2012c43e2b87784e6fa))
2. 더미데이터 삭제하고 완료페이지에서 값들 적용해서 보이게 했는데 사전테스트 완료페이지에서 관심 아티스트 값이 보이지 않음.
-> 여기서 이것저것 수정하다가 꼬인 거 같아요,,, 그러다가 스포티파이 api 관련 때문에 배포에서 해야만 되는 건지 테스트하기 위해서 우선 pr 올림 [feat/사전테스트프로필완료페이지 변경](https://github.com/UMC-Banddy/client/pull/142/commits/768fab0aa18326d19971418c3e88df20d688bcf2)
-> 머지함 
-> eslint오류 ,,,남.....ㅜㅜ 급해서 체크 안 하고 올렸더니 그랬나봐요 죄송합니다..  https://github.com/UMC-Banddy/client/actions/runs/17134780480/job/48607901337
-> …

fix: lint/type fixes for pretest pages( eslint 오류 수정 )

---

src/constants/index.ts
src/features/my/hooks/useProfile.ts
src/features/setting/hooks/useCurrentUser.ts
src/pages/Home/HomePage.tsx
src/pages/Home/_components/BandCarousel.tsx
src/pages/Home/_components/BandInfoModal.tsx
src/pages/Home/_components/HomeTagSection.tsx
src/pages/Home/_components/TagList.tsx
src/store/userStore.ts

fix: simliar 기능 해결

---

src/pages/Join/create_band/CreateBandGenre.tsx

- #이슈번호
- fix: 장르 'Metal' 안나오던 버그 수정

fix: 장르 'Metal' 안나오던 버그 수정

---

src/pages/Join/create_band/CreateBandGenre.tsx

fix: 장르 Metal 문구 수정
